package com.fitvision.shared.exception;

public enum ErrorCode {
    SIZE_CHART_NOT_FOUND,
    PRODUCT_NOT_FOUND,
    STORE_NOT_FOUND,
    BRAND_NOT_FOUND,
    INVALID_API_KEY,
    INVALID_BODY_MEASUREMENTS,
    UNAUTHORIZED,
    VALIDATION_ERROR,
    INTERNAL_ERROR
}
