package com.fitvision.shared.exception;

public enum ErrorCode {
    SIZE_CHART_NOT_FOUND,
    PRODUCT_NOT_FOUND,
    STORE_NOT_FOUND,
    BRAND_NOT_FOUND,
    INVALID_API_KEY,
    INVALID_BODY_MEASUREMENTS,
    UNAUTHORIZED,
    VALIDATION_ERROR,
    INTERNAL_ERROR,
    UNSUPPORTED_FILE_FORMAT,
    SIZE_CHART_PARSE_ERROR,
    INVALID_SECRET_KEY,
    STORE_ALREADY_EXISTS,
    INVALID_CREDENTIALS,
    ADMIN_ALREADY_EXISTS,
    SHOPIFY_CONNECT_ERROR
}
