-- FitVision initial schema
-- All PKs are UUID generated by the application.
-- Multi-tenant: every tenant-scoped table carries tenant_id.

-- ============================================================
-- stores (tenant root)
-- ============================================================
CREATE TABLE stores (
    id                  UUID            PRIMARY KEY,
    name                VARCHAR(255)    NOT NULL,
    email               VARCHAR(255)    NOT NULL UNIQUE,
    plan                VARCHAR(50)     NOT NULL,
    status              VARCHAR(50)     NOT NULL,
    api_key_public      VARCHAR(255)    NOT NULL UNIQUE,
    api_key_secret      VARCHAR(255)    NOT NULL,
    platform            VARCHAR(50)     NOT NULL,
    subscription_status VARCHAR(50)     NOT NULL,
    created_at          TIMESTAMP       NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMP       NOT NULL DEFAULT NOW()
);

-- ============================================================
-- brands
-- tenant_id is nullable: NULL means FitVision-managed global brand.
-- ============================================================
CREATE TABLE brands (
    id              UUID            PRIMARY KEY,
    tenant_id       UUID            REFERENCES stores(id),
    name            VARCHAR(255)    NOT NULL,
    slug            VARCHAR(255)    NOT NULL UNIQUE,
    source          VARCHAR(50)     NOT NULL,
    last_scraped_at TIMESTAMP,
    created_at      TIMESTAMP       NOT NULL DEFAULT NOW()
);

-- ============================================================
-- products (always tenant-scoped)
-- ============================================================
CREATE TABLE products (
    id                  UUID            PRIMARY KEY,
    brand_id            UUID            NOT NULL REFERENCES brands(id),
    tenant_id           UUID            NOT NULL REFERENCES stores(id),
    external_product_id VARCHAR(255)    NOT NULL,
    name                VARCHAR(255)    NOT NULL,
    category            VARCHAR(100)    NOT NULL,
    gender_target       VARCHAR(50)     NOT NULL,
    created_at          TIMESTAMP       NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMP       NOT NULL DEFAULT NOW(),
    UNIQUE (tenant_id, external_product_id)
);

-- ============================================================
-- size_charts
-- Only one version can be active per product at a time
-- (enforced at application layer, not DB constraint).
-- ============================================================
CREATE TABLE size_charts (
    id          UUID        PRIMARY KEY,
    product_id  UUID        NOT NULL REFERENCES products(id),
    version     INTEGER     NOT NULL,
    source      VARCHAR(50) NOT NULL,
    active      BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMP   NOT NULL DEFAULT NOW()
);

-- ============================================================
-- size_entries
-- All measurement columns are nullable — not every chart has
-- every dimension (e.g. some charts only track chest + waist).
-- ============================================================
CREATE TABLE size_entries (
    id              UUID            PRIMARY KEY,
    size_chart_id   UUID            NOT NULL REFERENCES size_charts(id),
    size_label      VARCHAR(20)     NOT NULL,
    chest_min       DECIMAL(5, 1),
    chest_max       DECIMAL(5, 1),
    waist_min       DECIMAL(5, 1),
    waist_max       DECIMAL(5, 1),
    hip_min         DECIMAL(5, 1),
    hip_max         DECIMAL(5, 1),
    height_min      DECIMAL(5, 1),
    height_max      DECIMAL(5, 1)
);

-- ============================================================
-- recommendation_requests (analytics — no cascade deletes)
-- FKs are RESTRICT by default: a store or product with
-- recommendation history cannot be deleted, preserving analytics.
-- ============================================================
CREATE TABLE recommendation_requests (
    id                      UUID            PRIMARY KEY,
    tenant_id               UUID            NOT NULL REFERENCES stores(id),
    product_id              UUID            NOT NULL REFERENCES products(id),
    height_cm               DECIMAL(5, 1)   NOT NULL,
    weight_kg               DECIMAL(5, 1)   NOT NULL,
    gender                  VARCHAR(20),
    age                     INTEGER,
    recommended_size        VARCHAR(20)     NOT NULL,
    confidence_score        DECIMAL(3, 2)   NOT NULL,
    body_measurements_stored BOOLEAN        NOT NULL DEFAULT FALSE,
    created_at              TIMESTAMP       NOT NULL DEFAULT NOW()
);

-- ============================================================
-- Indexes
-- ============================================================
CREATE INDEX idx_stores_api_key_public      ON stores(api_key_public);
CREATE INDEX idx_products_tenant_id         ON products(tenant_id);
CREATE INDEX idx_rec_requests_tenant_id     ON recommendation_requests(tenant_id);
CREATE INDEX idx_rec_requests_product_id    ON recommendation_requests(product_id);
